// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASdX9Pztw7feM7r9zmb63iLjb9DkUYxp0',
    appId: '1:334780662668:web:d71401fae65dafdeca8ca9',
    messagingSenderId: '334780662668',
    projectId: 'floracare-2121',
    authDomain: 'floracare-2121.firebaseapp.com',
    storageBucket: 'floracare-2121.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgBdKebVOY9M2QDt8C5wAXoMHLev8DTdM',
    appId: '1:334780662668:android:f9f605113b8a3d11ca8ca9',
    messagingSenderId: '334780662668',
    projectId: 'floracare-2121',
    storageBucket: 'floracare-2121.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIuVJ0UUkJUU2bxZ6SdyHWjUVXGiwcPh0',
    appId: '1:334780662668:ios:c1e96c47fecd1e8dca8ca9',
    messagingSenderId: '334780662668',
    projectId: 'floracare-2121',
    storageBucket: 'floracare-2121.firebasestorage.app',
    iosBundleId: 'com.example.floracare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIuVJ0UUkJUU2bxZ6SdyHWjUVXGiwcPh0',
    appId: '1:334780662668:ios:c1e96c47fecd1e8dca8ca9',
    messagingSenderId: '334780662668',
    projectId: 'floracare-2121',
    storageBucket: 'floracare-2121.firebasestorage.app',
    iosBundleId: 'com.example.floracare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASdX9Pztw7feM7r9zmb63iLjb9DkUYxp0',
    appId: '1:334780662668:web:56a584e3c2174fa0ca8ca9',
    messagingSenderId: '334780662668',
    projectId: 'floracare-2121',
    authDomain: 'floracare-2121.firebaseapp.com',
    storageBucket: 'floracare-2121.firebasestorage.app',
  );
}
