name: flora_care
description: Plant Care & Watering Reminder
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  sqflite: ^2.3.0
  path: ^1.8.3
  awesome_notifications:
    git:
      url: https://github.com/rafaelsetragni/awesome_notifications.git
      ref: master
  image_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true