// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdaSkJt_hSkgCAv7zgsleq_-13JBCZQT4',
    appId: '1:1014533092080:web:e2808855e2bba9aa400835',
    messagingSenderId: '1014533092080',
    projectId: 'fir-crud-basics-26257',
    authDomain: 'fir-crud-basics-26257.firebaseapp.com',
    storageBucket: 'fir-crud-basics-26257.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLZz6nhEzm5Sgsf-n0DoBthmKTb968o3Q',
    appId: '1:1014533092080:android:57db134b693daf9c400835',
    messagingSenderId: '1014533092080',
    projectId: 'fir-crud-basics-26257',
    storageBucket: 'fir-crud-basics-26257.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ1oco_Ig9IXjbJ-w0bBbsSU0Hr7ab2-8',
    appId: '1:1014533092080:ios:62f44ed96411ffc0400835',
    messagingSenderId: '1014533092080',
    projectId: 'fir-crud-basics-26257',
    storageBucket: 'fir-crud-basics-26257.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ1oco_Ig9IXjbJ-w0bBbsSU0Hr7ab2-8',
    appId: '1:1014533092080:ios:62f44ed96411ffc0400835',
    messagingSenderId: '1014533092080',
    projectId: 'fir-crud-basics-26257',
    storageBucket: 'fir-crud-basics-26257.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdaSkJt_hSkgCAv7zgsleq_-13JBCZQT4',
    appId: '1:1014533092080:web:dd865d89038cf3d4400835',
    messagingSenderId: '1014533092080',
    projectId: 'fir-crud-basics-26257',
    authDomain: 'fir-crud-basics-26257.firebaseapp.com',
    storageBucket: 'fir-crud-basics-26257.firebasestorage.app',
  );
}
